python run1/main.py
python run2/main.py
python run3/main.py
python run4/main.py
python run5/main.py
python run6/main.py
python run7/main.py
python run8/main.py
python run9/main.py
python run10/main.py
python run11/main.py
python run12/main.py
python run13/main.py
python run14/main.py
python run15/main.py
python run16/main.py
python run17/main.py
python run18/main.py
python run19/main.py
python run20/main.py
python run21/main.py
python run22/main.py
python run23/main.py
python run24/main.py
